services:
  - type: web
    name: castmap-admin
    env: node
    plan: free
    buildCommand: "npm install && npm run build:next"
    startCommand: "npm start"
    envVars:
      - key: PUBLIC_BASE_URL
        value: https://castmap.uz
